version: '3.7'
services:
  app:
    build: ./docker/local/php-fpm
    depends_on:
      - db
    volumes:
      - ./src:/app:cached
      - app-vendor-volume:/app/vendor
    working_dir: /app
  web:
    build: ./docker/local/nginx
    ports:
      - ${WEB_HTTP_PORT:-80}:80
    depends_on:
      - app
  db:
    build: ./docker/local/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-volume:/var/lib/mysql
      - ./docker/local/mysql/logs:/var/log/mysql:delegated
  mailhog:
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_SMTP_PORT:-1025}:1025
      - ${MAILHOG_HTTP_PORT:-8025}:8025
  doc-api:
    image: swaggerapi/swagger-ui
    ports:
      - ${DOC_API_PORT:-8080}:8080
    volumes:
      - ./document/openapi.yaml:/openapi.yaml:ro
    environment:
      SWAGGER_JSON: /openapi.yaml
  doc-db:
    build: ./docker/local/tbls
    volumes:
      - ./document:/work:delegated
    command: doc --force mysql://root:${DB_ROOT_PASSWORD:-root}@db:3306/${DB_DATABASE:-laravel}

volumes:
  app-vendor-volume:
  db-volume:
